version: '3.2'

services:
  db:
    image: postgres:9.6-alpine
    environment:
    - POSTGRES_DB=vote
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
    ports:
    - "5432:5432"
volumes:
  db-data: {}